# Homework 0 

Author : Jay Bendre

Date :  29th March, 2022 

In [29]:
# Importing all required libraries
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

### Question 1. 

Basic Exercises using Numpy, let  $u = (1,2,3,3,2,1)'$ 

a. Compute $U = I - \frac{2}{u'u} uu'$

In [30]:
# Initializing required u variable 
u = np.array([1,2,3,3,2,1]).T

# Identity Matrix
i = np.identity(u.shape[0])

# Getting the new transformation 
U = np.matrix(i - (2/ (u.T @ u)) * np.outer(u,u.T))

# Printing the new transformation
U

matrix([[ 0.92857143, -0.14285714, -0.21428571, -0.21428571, -0.14285714,
         -0.07142857],
        [-0.14285714,  0.71428571, -0.42857143, -0.42857143, -0.28571429,
         -0.14285714],
        [-0.21428571, -0.42857143,  0.35714286, -0.64285714, -0.42857143,
         -0.21428571],
        [-0.21428571, -0.42857143, -0.64285714,  0.35714286, -0.42857143,
         -0.21428571],
        [-0.14285714, -0.28571429, -0.42857143, -0.42857143,  0.71428571,
         -0.14285714],
        [-0.07142857, -0.14285714, -0.21428571, -0.21428571, -0.14285714,
          0.92857143]])

b. Let C = $UU$, find the largest and smallest off diagonal elements of C.

In [31]:
# Defining C = UU 
C = U @ U

print("Value of C matrix: \n", C)
# Off diagonal elements of C 

# Generating the mask 
mask = np.ones(C.shape)
# Generating boolean matrix 
mask = (mask - np.diag(np.ones(C.shape[0]))).astype(np.bool)


print("Minimum off diagonal element of C is: {} \nMaximum off diagonal element of C is: {}".format(
    np.amin(C[mask]), np.amax(C[mask])))

Value of C matrix: 
 [[ 1.00000000e+00 -3.50130922e-17 -5.16522766e-17 -5.16522766e-17
  -3.50130922e-17 -2.20911724e-17]
 [-3.50130922e-17  1.00000000e+00 -4.77934019e-17 -4.77934019e-17
  -1.45150332e-17 -1.64267692e-17]
 [-5.16522766e-17 -4.77934019e-17  1.00000000e+00 -8.38331672e-17
  -7.55489775e-17 -5.23957295e-17]
 [-5.16522766e-17 -4.77934019e-17 -8.38331672e-17  1.00000000e+00
  -7.55489775e-17 -5.23957295e-17]
 [-3.50130922e-17 -1.45150332e-17 -7.55489775e-17 -7.55489775e-17
   1.00000000e+00 -1.64267692e-17]
 [-2.20911724e-17 -1.64267692e-17 -5.23957295e-17 -5.23957295e-17
  -1.64267692e-17  1.00000000e+00]]
Minimum off diagonal element of C is: -8.383316716557304e-17 
Maximum off diagonal element of C is: -1.451503316633655e-17


c. Find largest and smallest diagonal elements of C

In [32]:
# Extracting diagonal elements from the matrix
diag_C = C.diagonal()
print("Minimum diagonal element of C is: {} \nMaximum diagonal element of C is: {}".format(np.min(diag_C), np.max(diag_C)))

Minimum diagonal element of C is: 0.9999999999999999 
Maximum diagonal element of C is: 1.0


d. Compute $Uu$

In [33]:
# Getting the dot product between vector and matrix
Uu = U @ u
print(Uu)

[[-1. -2. -3. -3. -2. -1.]]


e. Computer the scalar $max_i \sum_{j} |U_{ij}|$

In [34]:
# Getting rowise sums of the matrix
row_wise_sums = np.sum(np.abs(U), axis = 0)
print("The above scalar = {}".format(np.max(row_wise_sums)))

The above scalar = 2.2857142857142856


f. Print third row of U

In [35]:
print("Third Row of U matrix: \n", U[2,:])

Third Row of U matrix: 
 [[-0.21428571 -0.42857143  0.35714286 -0.64285714 -0.42857143 -0.21428571]]


g. Print the elements of the second column below the diagonal of U

In [36]:
# Extracting the second column and then selecting only elements below the diagonal
second_col_U = U[:,1][2:]
print("Elements in the second column below the diagonal: \n", second_col_U)

Elements in the second column below the diagonal: 
 [[-0.42857143]
 [-0.42857143]
 [-0.28571429]
 [-0.14285714]]


h. Let A be first 3 columns of U, Compute $P = AA'$

In [37]:
# Extracting first 3 columns
A = np.matrix(U[:,:3])

# Calculating P = A A^T
P = np.matrix(A @ A.T)

# Printing the matrix
print("Matrix P: \n", P)

Matrix P: 
 [[ 9.28571429e-01 -1.42857143e-01 -2.14285714e-01 -3.54025199e-17
  -2.88884563e-17 -1.44442281e-17]
 [-1.42857143e-01  7.14285714e-01 -4.28571429e-01 -1.52938886e-17
  -2.26576127e-18 -1.13288064e-18]
 [-2.14285714e-01 -4.28571429e-01  3.57142857e-01 -4.07837029e-17
  -4.30494642e-17 -2.15247321e-17]
 [-3.54025199e-17 -1.52938886e-17 -4.07837029e-17  6.42857143e-01
   4.28571429e-01  2.14285714e-01]
 [-2.88884563e-17 -2.26576127e-18 -4.30494642e-17  4.28571429e-01
   2.85714286e-01  1.42857143e-01]
 [-1.44442281e-17 -1.13288064e-18 -2.15247321e-17  2.14285714e-01
   1.42857143e-01  7.14285714e-02]]


i. Show that P is idempotent by recomputing (e) with $PP - P$

In [38]:
# Computing PP - P, Let it be X 
X = P @ P - P
row_wise_sums = np.sum(np.abs(X), axis = 0)
print("The above scalar = {}".format(np.max(row_wise_sums)))

The above scalar = 2.43852557194454e-16


Since all values in $PP - P \sim 0$, we can say that $P$ is a idempotent matrix. 

j. Let B be the last 3 columns of U, compute $Q = BB'$

In [39]:
# Getting B matrix from last 3 columns of U 
B = np.matrix(U[:,-3:])

# Computing Q = B B^T
Q = np.matrix(B @ B.T)

# Printing the matrix
print("Matrix Q: \n", Q)

Matrix Q: 
 [[ 7.14285714e-02  1.42857143e-01  2.14285714e-01 -2.38967009e-17
  -7.25751658e-18 -8.21338462e-18]
 [ 1.42857143e-01  2.85714286e-01  4.28571429e-01 -4.77934019e-17
  -1.45150332e-17 -1.64267692e-17]
 [ 2.14285714e-01  4.28571429e-01  6.42857143e-01 -2.83220159e-17
  -2.00378263e-17 -2.46401539e-17]
 [-2.38967009e-17 -4.77934019e-17 -2.83220159e-17  3.57142857e-01
  -4.28571429e-01 -2.14285714e-01]
 [-7.25751658e-18 -1.45150332e-17 -2.00378263e-17 -4.28571429e-01
   7.14285714e-01 -1.42857143e-01]
 [-8.21338462e-18 -1.64267692e-17 -2.46401539e-17 -2.14285714e-01
  -1.42857143e-01  9.28571429e-01]]


k. Show that $Q$ is idempotent by recomputing (e) with $QQ - Q$

In [40]:
# Computing QQ - Q, Let it be X 
X = Q @ Q - Q
row_wise_sums = np.sum(np.abs(X), axis = 0)
print("The above scalar = {}".format(np.max(row_wise_sums)))

The above scalar = 2.2069930916815132e-16


Since all values in $QQ - Q \sim 0$, we can say that $Q$ is a idempotent matrix. 

l. Compute P + Q

In [41]:
print(P + Q)

[[ 1.00000000e+00 -2.77555756e-17 -5.55111512e-17 -5.92992209e-17
  -3.61459728e-17 -2.26576127e-17]
 [-2.77555756e-17  1.00000000e+00 -5.55111512e-17 -6.30872905e-17
  -1.67807944e-17 -1.75596499e-17]
 [-5.55111512e-17 -5.55111512e-17  1.00000000e+00 -6.91057189e-17
  -6.30872905e-17 -4.61648860e-17]
 [-5.92992209e-17 -6.30872905e-17 -6.91057189e-17  1.00000000e+00
  -1.11022302e-16 -5.55111512e-17]
 [-3.61459728e-17 -1.67807944e-17 -6.30872905e-17 -1.11022302e-16
   1.00000000e+00  0.00000000e+00]
 [-2.26576127e-17 -1.75596499e-17 -4.61648860e-17 -5.55111512e-17
   0.00000000e+00  1.00000000e+00]]


### Question 2.

Read in the matrix in the file ‘oringp.dat’ (available on Piazza) on the failure of O-rings leading to the
Challenger disaster. The columns are flight number, date, number of O-rings, number failed, and temperature
at launch. Compute the correlation between number of failures and temperature at launch, deleting the last,
missing observation (the disaster)

In [42]:
# Importing the file 

df = pd.read_csv("oringp.dat", header = None, sep = '\s+', engine = 'python')
df.columns = ['FlightNumber', 'date', 'no_o_rings','fail','temp']
df.head()

# Dropping the last missing value 
df = df.dropna(axis = 0)

# Converting the failure column to integer
df['fail'] = df['fail'].astype(int)

# Preview into dataset
df.head()


FlightNumber      date  no_o_rings  fail  temp
0            1   4/12/81           6     0    66
1            2  11/12/81           6     1    70
2            3   3/22/82           6     0    69
3            5  11/11/82           6     0    68
4            6   4/04/83           6     0    67

In [43]:
# Finding the correlation between failure and temperature
np.corrcoef(df['fail'], df['temp'])

array([[ 1.        , -0.56132843],
       [-0.56132843,  1.        ]])

Hence we can see that $corr(fail, temp) = -0.56132$

### Question 3. 
Consider the mixed effect model 
$$
y_i = x_i' \beta + z_i' \gamma + \epsilon_i, \quad i = 1, \dots, n,
$$
where $\epsilon_i \sim N(0, \sigma_0^2)$ are independent normal errors, $\beta \in \mathbb{R}^p$ are fixed effects, $\gamma \in \mathbb{R}^q$ are random effects assumed to be $N(0_q, \sigma_1^2 I_q)$, $\gamma$ and $\epsilon_i$ are independent. For simplicity, assume $\mu_i = x_i' \beta$. 
Let $ y = (y_1, \dots, y_n)'$, $ \mu = (\mu_1, \dots, \mu_n)'$, 
$ Z = (z_1, \dots, z_n)'$, 
then
$ y \in \mathbb{R}^{n}$, $ \mu \in \mathbb{R}^n$, $ Z \in \mathbb{R}^{n \times q}$,
and 
$ y \sim N( \mu, \sigma_1^2 ZZ'  + \sigma_0^2 I_n)$.
The log-density function is given by
$$
 -\frac{n}{2} \log(2 \pi) - \frac{1}{2} \log (\det(\sigma_1^2 ZZ' + \sigma_0^2 I_n)) - \frac{1}{2} (y-\mu)'(\sigma_1^2 ZZ' + \sigma_0^2I_n)^{-1} (y-\mu).
$$

Please write a function, call it 
$\mathsf{dmvnorm\_lowrank(y, mu, Z, sigma0, sigma1, log = FALSE)}$
that evaluates the (log)-density function at a given $y \in \mathbb{R}^n$.
Choose values for $n (> 5)$ and $q (> 3)$, test your function on simulated data.

Notes: 
1) When $\mathsf{log = FALSE}$, your function should calculate the log likelihood; when 
$\mathsf{log = TRUE}$, your function should calculate the original likelihood function. 
The default uses $\mathsf{log = FALSE}$. 
2) Use the $\mathsf{np.random.seed}$ function before generating data from a random distribution.

In [44]:
# Creating new function called dmvnorm_lowrank 

def dmvnorm_lowrank(y,mu,Z,sigma0,sigma1,log = False):
    # Calculating all the terms required in the given log likelihood function function 
    
    #a. Z * Z^T
    z_zt = Z @ Z.T
    
    #b. n 
    n = y.shape[0]
    
    #c. sigma0^2 * In
    sigma0_identity = sigma0**2 * np.identity(n)
    
    # Calculating the log density of the function 
    ldf  = -(n/2) * np.log(2*np.pi) -1/2 * np.log(np.linalg.det(sigma1**2 * z_zt + sigma0_identity)) - 1/2 * (y - mu).T @ np.linalg.inv((sigma1**2 * z_zt + sigma0_identity)) @ (y - mu)
    
    # Checking whether the function demands the likelihood to be in log space or not
    if log:
        return np.exp(ldf)
    else:
        return ldf

For testing, we assume the following constraints: 

* $n = 100$ , $q = 5$

* $\sigma_0 \sim$ Random number between 0 and 100 

* $\sigma_1 \sim$ Random number between 0 and 100 

* $\mu \sim Uniform(0,10)$

* $Z \sim N (10,2)$ 

* $y \sim N(\mu, \sigma_1^2 ZZ' + \sigma_0^2 I_n)$




In [45]:
# Testing the above function to get the likelihood for random Y and mu

# Generating Z matrix with n = 100 and q = 5 
np.random.seed(920211348)

# Generating sigma 0 and sigma 1 
sigma0 = np.random.randint(100)
sigma1 = np.random.randint(100)
mu = np.random.uniform(0,10,100)

# Generating 500 values from a normal distribution with mean 10 and standard deviation 2
Z = np.random.normal(10,2,500).reshape(100,5)

# Generating 100 values from the multivariate normal distribution with mean mu and covariance matrix Z @ Z.T
y = np.random.multivariate_normal(mu, sigma1**2 * np.identity(100) + sigma0**2 * Z @ Z.T, 1).reshape(100,1)

In [46]:
# Calculating the likelihood for the above generated data 

#a. Log Likelihood 
log_likelihood = dmvnorm_lowrank(y,mu,Z,sigma0,sigma1,log = False)

#b. Normal Likelihood
likelihood = dmvnorm_lowrank(y,mu,Z,sigma0,sigma1,log = True)
